---
- hosts: centos_servers
  tasks:
  - name: Update all installed package using YUM module
    become: true
    yum:
       name: '*'
       state: latest
       update_cache: yes
       update_only: yes
    register: yum_update_status    
   
  - name: Reboot when package were updated
    reboot:
    when: yum_update_status.changed

 
  
